// GENERATED by scripts/generate-alerts-sky.js from index.html. Do not edit:
// change index.html and re-run the script. alerts.test.js checks it is current.

const D2R = Math.PI / 180,
  R2D = 180 / Math.PI;
const rev = x => (x % 360 + 360) % 360;
const sin = d => Math.sin(d * D2R),
  cos = d => Math.cos(d * D2R);
const asin = x => Math.asin(Math.max(-1, Math.min(1, x))) * R2D;
const atan2 = (y, x) => Math.atan2(y, x) * R2D;
const acos = x => Math.acos(Math.max(-1, Math.min(1, x))) * R2D;
const jd = date => date.getTime() / 86400000 + 2440587.5;
const gmst = date => rev(280.46061837 + 360.98564736629 * (jd(date) - 2451545.0));
function sunAltitude(date, lat, lonE) {
  const yr = date.getUTCFullYear();
  const start = Date.UTC(yr, 0, 1);
  const days = yr % 4 === 0 && yr % 100 !== 0 || yr % 400 === 0 ? 366 : 365;
  const doy = (date.getTime() - start) / 86400000;
  const hUTC = date.getUTCHours() + date.getUTCMinutes() / 60 + date.getUTCSeconds() / 3600;
  const g = 2 * Math.PI / days * (doy + (hUTC - 12) / 24);
  const eq = 229.18 * (0.000075 + 0.001868 * Math.cos(g) - 0.032077 * Math.sin(g) - 0.014615 * Math.cos(2 * g) - 0.040849 * Math.sin(2 * g));
  const decl = 0.006918 - 0.399912 * Math.cos(g) + 0.070257 * Math.sin(g) - 0.006758 * Math.cos(2 * g) + 0.000907 * Math.sin(2 * g) - 0.002697 * Math.cos(3 * g) + 0.00148 * Math.sin(3 * g);
  const tst = hUTC * 60 + eq + 4 * lonE;
  const ha = tst / 4 - 180;
  const cosZ = Math.sin(lat * D2R) * Math.sin(decl) + Math.cos(lat * D2R) * Math.cos(decl) * Math.cos(ha * D2R);
  return 90 - acos(cosZ);
}
function moonState(date, lat, lonE) {
  const d = jd(date) - 2451543.5;
  const ws = 282.9404 + 4.70935e-5 * d,
    Ms = rev(356.0470 + 0.9856002585 * d),
    Ls = rev(ws + Ms);
  const N = rev(125.1228 - 0.0529538083 * d),
    i = 5.1454,
    w = rev(318.0634 + 0.1643573223 * d);
  const e = 0.054900,
    M = rev(115.3654 + 13.0649929509 * d);
  const Lm = rev(N + w + M),
    Dm = rev(Lm - Ls),
    F = rev(Lm - N);
  let E = M + R2D * e * sin(M) * (1 + e * cos(M));
  for (let k = 0; k < 6; k++) E = E - (E - R2D * e * sin(E) - M) / (1 - e * cos(E));
  const xv = 60.2666 * (cos(E) - e),
    yv = 60.2666 * (Math.sqrt(1 - e * e) * sin(E));
  const v = rev(atan2(yv, xv)),
    r = Math.sqrt(xv * xv + yv * yv);
  let xh = r * (cos(N) * cos(v + w) - sin(N) * sin(v + w) * cos(i));
  let yh = r * (sin(N) * cos(v + w) + cos(N) * sin(v + w) * cos(i));
  let zh = r * (sin(v + w) * sin(i));
  let lon = rev(atan2(yh, xh)),
    latM = atan2(zh, Math.sqrt(xh * xh + yh * yh));
  lon += -1.274 * sin(M - 2 * Dm) + 0.658 * sin(2 * Dm) - 0.186 * sin(Ms) - 0.059 * sin(2 * M - 2 * Dm) - 0.057 * sin(M - 2 * Dm + Ms) + 0.053 * sin(M + 2 * Dm) + 0.046 * sin(2 * Dm - Ms) + 0.041 * sin(M - Ms) - 0.035 * sin(Dm) - 0.031 * sin(M + Ms) - 0.015 * sin(2 * F - 2 * Dm) + 0.011 * sin(M - 4 * Dm);
  latM += -0.173 * sin(F - 2 * Dm) - 0.055 * sin(M - F - 2 * Dm) - 0.046 * sin(M + F - 2 * Dm) + 0.033 * sin(F + 2 * Dm) + 0.017 * sin(2 * M + F);
  const ecl = 23.4393 - 3.563e-7 * d;
  const xg = cos(lon) * cos(latM),
    yg = sin(lon) * cos(latM),
    zg = sin(latM);
  const ye = yg * cos(ecl) - zg * sin(ecl),
    ze = yg * sin(ecl) + zg * cos(ecl);
  const ra = rev(atan2(ye, xg)),
    dec = atan2(ze, Math.sqrt(xg * xg + ye * ye));
  let ha = rev(rev(gmst(date) + lonE) - ra);
  if (ha > 180) ha -= 360;
  const alt = asin(sin(lat) * sin(dec) + cos(lat) * cos(dec) * cos(ha));
  const az = rev(atan2(sin(ha), cos(ha) * sin(lat) - Math.tan(dec * D2R) * cos(lat)) + 180);
  const elong = rev(Lm - Ls);
  return {
    alt,
    az,
    r, // geocentric distance in Earth radii — used for semi-diameter/parallax in sight reduction
    illum: (1 - cos(elong)) / 2,
    age: elong / 360 * 29.53
  };
}
function scoreHours(wx, loc, startMs, endMs) {
  const H = wx && wx.hourly;
  if (!H || !H.time || !H.time.length) return [];
  const off = (wx.utc_offset_seconds || 0) * 1000;
  const cloud = H.cloud_cover || [], high = H.cloud_cover_high || [], precip = H.precipitation_probability || [];
  const out = [];
  for (let i = 0; i < H.time.length; i++) {
    const t = Date.parse(H.time[i] + "Z") - off; // local wall-clock -> true epoch
    if (isNaN(t) || t < startMs || t > endMs) continue;
    const d = new Date(t);
    const alt = sunAltitude(d, loc.lat, loc.lon);
    if (alt > -6) continue; // daylight / civil twilight: not observing time
    const m = moonState(d, loc.lat, loc.lon);
    const moonPen = m.alt > 0 ? m.illum * Math.min(1, m.alt / 40) * 2.2 : 0;
    const c = cloud[i] == null ? 0 : cloud[i];
    const hi = high[i] == null ? 0 : high[i];
    const pp = precip[i] == null ? 0 : precip[i];
    const precipFactor = pp >= 60 ? 0.15 : pp >= 30 ? 0.6 : 1;
    const clarity = (1 - c / 100) * (1 - 0.4 * hi / 100) * precipFactor;
    const moonFactor = Math.max(0, Math.min(1, 1 - moonPen / 2.2));
    out.push({ t, astro: alt <= -12, score: 100 * clarity * moonFactor, cloud: c, precip: pp, moonPen });
  }
  return out;
}
function summarize(hours) {
  if (!hours.length) return null;
  const astroHours = hours.filter(h => h.astro);
  const pool = astroHours.length ? astroHours : hours; // prefer true astronomical darkness
  let best = pool[0], bestVal = pool[0].score;
  for (let i = 0; i < pool.length; i++) {
    const a = pool[i].score, b = i + 1 < pool.length ? pool[i + 1].score : a;
    const v = (a + b) / 2; // best contiguous ~2h block
    if (v > bestVal) { bestVal = v; best = pool[i]; }
  }
  const score = Math.round(bestVal);
  let factor;
  if (!astroHours.length) factor = "no astro-dark";
  else if (best.precip >= 50) factor = "rain likely";
  else if (score >= 78) factor = "clear & dark";
  else {
    const cloudDef = best.cloud / 100, moonDef = best.moonPen / 2.2;
    factor = cloudDef >= moonDef ? (best.cloud >= 60 ? "cloudy" : "some cloud") : "moonlit";
  }
  return { score, factor, bestMs: best.t, astro: astroHours.length > 0, hours: pool };
}
function clearDarkScore(wx, loc, bortle, nowMs) {
  if (!wx || !wx.hourly || !wx.hourly.time || !wx.hourly.time.length) return null;
  const hours = scoreHours(wx, loc, nowMs - 1800000, nowMs + 18 * 3600000);
  if (!hours.length) return { score: null, factor: "no night ahead", astro: false, hours: [] };
  return summarize(hours);
}

export { sunAltitude, moonState, clearDarkScore };
